name       : ebtables
version    : 2.0.10_4
release    : 6
source     :
    - ftp://ftp.netfilter.org/pub/ebtables/ebtables-v2.0.10-4.tar.gz : dc6f7b484f207dc712bfca81645f45120cb6aee3380e77a1771e9c34a9a4455d
license    : GPL-2.0
component  : network.base
summary    : Linux-based bridging firewall.
description: Linux-based bridging firewall.
libsplit   : no
clang      : no
build      : |
    unset LD_AS_NEEDED
    export CFLAGS="${CFLAGS/-Wl,as-needed/}"
    %make CFLAGS="$CFLAGS  -Wno-error=unused-but-set-variable"
install    : |
    %make_install LIBDIR=%libdir% MANDIR=/usr/share/man SYSCONFIGDIR=/etc BINDIR=/usr/bin
    rm -rvf $installdir/etc/rc.d
    touch $installdir/etc/ebtables.conf
